# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: '30 5 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      pull-requests: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Python, pipenv
      uses: palewire/install-python-pipenv-pipfile@v2
      with:
        python-version: 3.11
    - name: Run pylint
      run: pipenv run pylint scripts_python
    - name: Run unit tests
      run: pipenv run pytest --cov
    - name: Pytest Coverage Commentator
      uses: coroo/pytest-coverage-commentator@bf2d76a0d38a8bbf7292aba469ae5285c5ea9660
      with:
        # Where to find the txt output of pytest-coverage
        pytest-coverage: .coverage
        # GITHUB_TOKEN
        token: ${{ github.token }}
